// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elrmhkaqyqaonvrzmogt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVscm1oa2FxeXFhb252cnptb2d0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNTc1OTUsImV4cCI6MjA2MjYzMzU5NX0.zSPG1nEpCWPr3W_5Z0vG-XN0n9PpGwiD_XmP0PCcQxE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);